# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21af931edaf3b1886ddd8a78888ed18a93d82d362ba3071e916c4deaf4b282ad01cad1ac038a3ddd8ae1d4eaf25cf855c04a320798e054ceb7155b1dd49c4878

test:
  secret_key_base: 69eb1632f127590d0bfb02ceec1ac3a24be38c704918d5b4a704d0b9b294fcd6edef6828844fe762173a68905537aed52c241eaa82b5ef7b2329cc413fae4243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
